# Generated by Django 5.2.9 on 2026-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('category', models.CharField(blank=True, choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Action', 'Action'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Crime', 'Crime'), ('Family', 'Family')], default='Comedy', max_length=50)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('hls_480p_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hls_720p_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hls_1080p_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
