# Generated by Django 5.2.9 on 2026-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content', '0002_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Action', 'Action'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Crime', 'Crime'), ('Family', 'Family')], default='Comedy', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
