# Generated by Django 5.2.9 on 2026-01-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content', '0003_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
